[config.wallpaper]
command = "swww"
arguments = ["query"]
set = true

[templates.waybar]
input_path = "./templates/ags/colors.scss"
output_path = "~/.config/ags/colors.scss"
post_hook = "pkill -SIGUSR2 ags"
