[config]
command = "sh"
arguments = ["-c", "swww query | awk -F'image: ' '{print $2}'"]
set = true

[templates.waybar]
input_path = "./templates/waybar/ags/colors.scss"
output_path = "~/.config/ags/styles/colors.scss"
post_hook = "pkill -SIGUSR1 ags"

[templates.kitty]
input_path = './templates/kitty/colors.conf'
output_path = '~/.config/kitty/themes/templates-matugen.conf'
post_hook = 'kitty +kitten themes --reload-in=all templates-matugen && pkill -SIGUSR1 kitty'

[templates.hyprland]
input_path = './templates/hyprland/colors.conf'
output_path = '~/.config/hypr/hyprland/colors.conf'
post_hook = 'hyprctl reload'