name: "Bugs"
description: "Anything happening not as expected. Vanillia version only."
assignees: "enessmr"
labels: "bug"

body:
- type: markdown
  attributes:
    value: "## Welcome!"
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug! If you need real-time help, join us on Discord.
