#general {
 #   ignore_dbus_inhibit = false
#}

#general {
#    lock_cmd = qs -p ~/.config/quickshell/lockShell.qml ipc call lock activate && pw-play ~/.config/hypr/sfx/yoshi-come.mp3 &             # avoid starting multiple hyprlock instances.
#    before_sleep_cmd = loginctl lock-session && pw-play ~/.config/hypr/sfx/yoshi-ha.mp3 &                                                        # lock before suspend.
#    after_sleep_cmd = hyprctl dispatch dpms on && pw-play ~/.config/hypr/sfx/yoshi-hoo.mp3 &        # to avoid having to press a key twice to turn on the display.
#}

# Screenlock
#listener {
    # HYPRLOCK TIMEOUT
#    timeout = 999999999999999999999999999999999999999999999999999999999999999999999999999999999
    # HYPRLOCK ONTIMEOUT
#    on-timeout = qs -p ~/.config/quickshell/lockShell.qml ipc call lock activate && pw-play ~/.config/hypr/sfx/yoshi-come.mp3 && loginctl lock-session
#}

# dpms
#listener {
    # DPMS TIMEOUT
#    timeout = 99999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999999
    # DPMS ONTIMEOUT
#    on-timeout = hyprctl dispatch dpms off
    # DPMS ONRESUME
#    on-resume = hyprctl dispatch dpms on
#}

# Suspend
#listener {
    # SUSPEND TIMEOUT
#    timeout = 1800
    #SUSPEND ONTIMEOUT
#    on-timeout = systemctl suspend
#p}