# 💚 ✨ HyprYogShgiThrii ✨ 🦕

######## 🥵 Goober's goon vindov rules 🥵 ########
# windowrule = tile, class:^(Microsoft-edge)$ # fuck this shit
windowrule = match:class = Brave-browser, tile on

windowrule = match:class = ^(Chromium)$, tile on

windowrule = match:class = ^(blueman-manager)$, float on

windowrule = match:class = ^(blueberry.py)$, float on

windowrule = match:class = ^(nm-connection-editor)$, float on

windowrule = match:class = ^(qalculate-gtk)$, float on

windowrule {
  name = steam-fix
  match:class = steam
  float = on
  stay_focused = on
  min_size = 1 1
}

windowrule = match:title = ^(Volume Control)(.*)$, float on

windowrule = match:title = ^(Smile)(.*)$, float on


# 🥵 Goober's goon Xgoonervideobridge rules 🥵
windowrule {
  name = Xgoonervideobridge
  match:class = ^(xwaylandvideobridge)$
  opacity = 0.0 override
  no_anim = on
  no_initial_focus = on
  max_size = 1 1
  no_blur = on
}


# 🥵 Goober's goon dialog rules 🥵
windowrule = match:title = ^(Open File)(.*)$, float on

windowrule = match:title = ^(Select a File)(.*)$, float on

windowrule = match:title = ^(Choose wallpaper)(.*)$, float on

windowrule = match:title = ^(Open Folder)(.*)$, float on

windowrule = match:title = ^(Save As)(.*)$, float on

windowrule = match:title = ^(Library)(.*)$, float on

windowrule = match:title = ^(File Upload)(.*)$, float on


# 🥵 Goober's goon vindov title rules 🥵
windowrule {
  name = Bar
  match:title = ^(Bar)$
  float = on
  border_size = 0
}

windowrule {
  name = wayneko
  match:title = ^(wayneko)$
  float = on
  border_size = 0
}

windowrule {
  name = HyprYoshi3 Gooner Emoji Picker 💚🦕😍💦🥵
  match:title = ^(HyprYoshi3 Gooner Emoji Picker 💚🦕😍💦🥵)(.*)$
  float = on
  border_size = 0
}

windowrule {
  name = HyprYoshi3 Gooner Settings 💚🦕😍💦🥵
  match:title = ^(HyprYoshi3 Gooner Settings 💚🦕😍💦🥵)(.*)$
  float = on
  border_size = 0
  rounding = 16
  no_shadow = on
  no_dim = on
  min_size = 1000 600
}

windowrule {
  name = HyprYoshi3 Gooner Artificial Unintelligence 💚🦕😍💦🥵
  match:title = ^(HyprYoshi3 Gooner Artificial Unintelligence 💚🦕😍💦🥵)(.*)$
  float = on
  border_size = 0
  min_size = 900 600
}

windowrule {
  name = Super Mario 64 PC Port
  match:class = ^(sm64.us.f3dex2e)$
  size = 640 480
  float = on
  border_size = 0
  center = on
  immediate = on
  no_blur = on
  opaque = on
  render_unfocused = on
  force_rgbx = on
}

windowrule {
  name = HyprYoshi3 Gooner Uncalculator 💚🦕😍💦🥵
  match:title = ^(HyprYoshi3 Gooner Uncalculator 💚🦕😍💦🥵)(.*)$
  float = on
  border_size = 0
}


# 🥵 Goober's goon tear (goon juice vith homemade special sauce dlc) rules 🥵
windowrule = match:class = .*\.exe, immediate on

windowrule = match:class = (steam_app)455, immediate on

windowrule = match:title = ^(neko)$, immediate on


######## 🥵 Goober's goon layer rules 🥵 ########
# layerrule = xray 1, .*
# layerrule = noanim, .*
layerrule = match:namespace = walker, no_anim on

layerrule = match:namespace = selection, no_anim on

layerrule = match:namespace = overview, no_anim on

layerrule = match:namespace = anyrun, no_anim on

layerrule = match:namespace = popup.*, no_anim on

layerrule = match:namespace = hyprpicker, no_anim on

layerrule = match:namespace = noanim, no_anim on

layerrule {
  name = GTK4 Layer Shell
  match:namespace = gtk4-layer-shell
  blur = on
  ignore_alpha = 0
}

layerrule {
  name = Applauncher
  match:namespace = launcher
  blur = on
  ignore_alpha = 0.5
}

layerrule = match:namespace = quickshell:screenCorners, animation popin 120%

layerrule = match:namespace = quickshell:notificationPopup, animation fade

layerrule {
  name = Notifications
  match:namespace = notifications
  blur = on
  ignore_alpha = 0.69
}