# 💚 ✨ HyporYogShgiThrii ✨ 🦕

# ######## 🥵 Goober's goon vindov rules 🥵 ########
# windowrule = tile, class:^(Microsoft-edge)$ # fuck this shit
windowrule = tile, class:^(Brave-browser)$
windowrule = tile, class:^(Chromium)$
windowrule = float, class:^(blueman-manager)$
windowrule = float, class:^(blueberry.py)$
windowrule = float, class:^(nm-connection-editor)$
windowrule = float, class:^(qalculate-gtk)$
windowrule = float, class:^(steam)$
windowrule = stayfocused, title:^()$, class:^(steam)$
windowrule = minsize 1 1, title:^()$, class:^(steam)$
windowrule = float, title:^(Volume Control)(.*)$
windowrule = float, title:^(Smile)(.*)$

# 🥵 Goober's goon Xgoonervideobridge rules 🥵
windowrule = opacity 0.0 override, class:^(xwaylandvideobridge)$
windowrule = noanim, class:^(xwaylandvideobridge)$
windowrule = noinitialfocus, class:^(xwaylandvideobridge)$
windowrule = maxsize 1 1, class:^(xwaylandvideobridge)$
windowrule = noblur, class:^(xwaylandvideobridge)$

# 🥵 Goober's goon dialog rules 🥵
windowrule = float, title:^(Open File)(.*)$
windowrule = float, title:^(Select a File)(.*)$
windowrule = float, title:^(Choose wallpaper)(.*)$
windowrule = float, title:^(Open Folder)(.*)$
windowrule = float, title:^(Save As)(.*)$
windowrule = float, title:^(Library)(.*)$
windowrule = float, title:^(File Upload)(.*)$
# 🥵 Goober's goon vindov title rules 🥵
windowrulev2 = float, noborder, title:Bar
windowrulev2 = float, noborder, title:^(wayneko)$
windowrulev2 = float, noborder, title:^(HyprYoshi3 Gooner Emoji Picker 💚🦕😍💦🥵)(.*)$
windowrulev2 = float, noborder, title:^(HyprYoshi3 Gooner Settings 💚🦕😍💦🥵)(.*)$
windowrule = rounding 16, title:^(HyprYoshi3 Gooner Settings 💚🦕😍💦🥵)(.*)$
windowrule = noshadow, nodim, title:^(HyprYoshi3 Gooner Settings 💚🦕😍💦🥵)(.*)$
windowrule = minsize 1000 600, title:^(HyprYoshi3 Gooner Settings 💚🦕😍💦🥵)(.*)$
windowrulev2 = float, noborder, title:^(HyprYoshi3 Gooner Artificial Unintelligence 💚🦕😍💦🥵)(.*)$
windowrule = minsize 900 600, title:^(HyprYoshi3 Gooner Artificial Unintelligence 💚🦕😍💦🥵)(.*)$
windowrulev2 = size 640 480, class:^(sm64.us.f3dex2e)$
windowrulev2 = float, noborder, class:^(sm64.us.f3dex2e)$
windowrulev2 = float, noborder, title:^(HyprYoshi3 Gooner Uncalculator 💚🦕😍💦🥵)(.*)$
windowrulev2 = center, class:^(sm64.us.f3dex2e)$
windowrulev2 = immediate, class:^(sm64.us.f3dex2e)$
windowrulev2 = noblur, class:^(sm64.us.f3dex2e)$
windowrulev2 = opaque, class:^(sm64.us.f3dex2e)$
windowrulev2 = renderunfocused, class:^(sm64.us.f3dex2e)$
windowrulev2 = forcergbx, class:^(sm64.us.f3dex2e)$

# 🥵 Goober's goon tear (goon juice vith homemade special sauce dlc) rules 🥵
windowrule = immediate, class:.*\.exe
windowrule = immediate, class:(steam_app)455
windowrule = immediate, title:^(neko)

# ######## 🥵 Goober's goon layer rules 🥵 ########
# layerrule = xray 1, .*
# layerrule = noanim, .*
layerrule = noanim, walker
layerrule = noanim, selection
layerrule = noanim, overview
layerrule = noanim, anyrun
layerrule = noanim, popup.*
layerrule = noanim, hyprpicker

layerrule = noanim, noanim
layerrule = blur, gtk4-layer-shell
layerrule = ignorezero, gtk4-layer-shell
layerrule = blur, launcher
layerrule = ignorealpha 0.5, launcher
layerrule = blur, notifications
layerrule = ignorealpha 0.69, notifications
layerrule = animation popin 120%, quickshell:screenCorners
layerrule = animation fade, quickshell:notificationPopup
layerrule = blur, notifications
layerrule = ignorealpha 0.69, notifications