# .github/workflows/mirror-to-gitlab.yml
name: Mirror to GitLab

on:
  push:
    branches: ["main"]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Push to GitLab
        run: |
          git remote add gitlab https://gitlab-ci-token:${{ secrets.GITLAB_TOKEN }}@gitlab.com/enessmr/hyprmaterial3.git
          git push --mirror gitlab
