# .github/workflows/mirror-to-gitlab.yml
name: Mirror to GitLab

on:
  push:
    branches: ["main"]

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Push to GitLab
        run: |
          git clone --mirror https://github.com/enessmr/hyprmaterial3.git
          cd hyprmaterial3.git
          git remote set-url --push origin https://gitlab.com/enessmr/hyprmaterial3.git
          git push --mirror
